---
- name: Create diverts configuration string
  ansible.builtin.set_fact:
    diverts: "{{ diverts | default([]) + [ lookup('template', 'diverts.broker.xml.j2') ] }}"
  loop: "{{ activemq_diverts }}"
  loop_control:
    loop_var: divert
    label: "{{ divert.name }}"

- name: Ensure diverts element exists in broker.xml
  ansible_middleware.amq.xml:
    path: "{{ activemq.instance_home }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:diverts
    input_type: xml
    state: present
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  become: yes

- name: Create diverts configuration in broker.xml
  ansible_middleware.amq.xml:
    path: "{{ activemq.instance_home }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:diverts
    input_type: xml
    set_children: "{{ diverts }}"
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
  become: yes
  notify:
    - restart amq_broker with no config refresh
