---
- name: Create diverts in broker.xml
  when: not activemq_modular_configuration
  become: true
  block:
    - name: Create diverts configuration string
      ansible.builtin.set_fact:
        diverts: "{{ diverts | default([]) + [ lookup('template', 'diverts.broker.xml.j2') ] }}"
      loop: "{{ activemq_diverts }}"
      loop_control:
        loop_var: divert
        label: "{{ divert.name }}"

    - name: Ensure diverts element exists in broker.xml
      middleware_automation.common.xml:
        path: "{{ activemq.instance_home }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:diverts
        input_type: xml
        state: present
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: true
      become: true

    - name: Create diverts configuration in broker.xml
      middleware_automation.common.xml:
        path: "{{ activemq.instance_home }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:diverts
        input_type: xml
        set_children: "{{ diverts }}"
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: true
      become: true
      notify:
        - restart amq_broker with no config refresh

- name: Create modular diverts configuration
  when: activemq_modular_configuration
  become: true
  block:
    - name: Remove diverts element from broker.xml
      middleware_automation.common.xml:
        path: "{{ activemq.instance_home }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:diverts
        state: absent
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
      notify:
        - restart amq_broker with no config refresh

    - name: Create diverts file
      ansible.builtin.template:
        src: modular/diverts.xml.j2
        dest: "{{ activemq.instance_home }}/etc/diverts.xml"
        owner: "{{ activemq_service_user }}"
        group: "{{ activemq_service_group }}"
        mode: '0644'
      notify:
        - touch broker.xml
        - restart amq_broker with no config refresh

    - name: Search diverts module in broker.xml
      ansible.builtin.find:
        paths: "{{ activemq.instance_home }}/etc/"
        patterns: broker.xml
        contains: '<xi:include.*/etc/diverts.xml'
        file_type: file
        use_regex: false
        read_whole_file: true
      changed_when: false
      check_mode: true
      register: module_presence

    - name: Include diverts module in broker.xml
      middleware_automation.common.xml:
        path: "{{ activemq.instance_home }}/etc/broker.xml"
        xpath: /conf:configuration/core:core/xi:include[@href='{{ activemq.instance_home }}/etc/diverts.xml']
        state: present
        input_type: xml
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
          xi: http://www.w3.org/2001/XInclude
        pretty_print: true
      when: module_presence.matched == 0
      notify:
        - restart amq_broker
