---
- name: "Start and enable instance {{ activemq.instance_name }} for {{ activemq.service_name }} service"
  throttle: 1
  ansible.builtin.systemd:
    name: "{{ activemq.instance_name }}"
    enabled: true
    state: started
  become: true
