---
- name: Playbook to deploy activemq in master/standby with shared datadir
  hosts: all
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_disable_mqtt_protocol: true
    activemq_shared_storage: true
    activemq_configure_firewalld: true
  roles:
   - middleware_automation.amq.activemq
  pre_tasks:
    - name: Create nfs shared directory
      ansible.builtin.file:
        state: directory
        path: /opt/amq/amq-broker/data/shared
        owner: root
        group: root
        mode: 0775
    - name: Create mount NFS volume
      ansible.posix.mount:
       src: 10.0.153.34:/nfs
       path: /opt/amq/amq-broker/data/shared
       opts: rw,sync,hard,intr
       state: mounted
       fstype: nfs
